# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.cache/wt [current_project]
set_property parent.project_path D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/counter.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/rst_bridge.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/sync_dff.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/dvi_tx_clkgen.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/rgb_timing.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/graphics.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/rgb_pattern.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/tmds_encoder.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/oserdes_ddr_10_1.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/rgb_to_dvi.vhd
  D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/sources_1/imports/sources/dvi_tx.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/constrs_1/imports/sources/arty-z7.xdc
set_property used_in_implementation false [get_files D:/Chestii/Programin_thingz/Vivado/Projects/graphics/graphics.srcs/constrs_1/imports/sources/arty-z7.xdc]


synth_design -top dvi_tx -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dvi_tx.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dvi_tx_utilization_synth.rpt -pb dvi_tx_utilization_synth.pb"
